"""add users and shipment customer

Revision ID: 0a8968878aa0
Revises: bc0216e87869
Create Date: 2026-09-03 05:26:48.941910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0a8968878aa0'
down_revision: Union[str, Sequence[str], None] = 'bc0216e87869'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('shipments', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_shipments_customer_id'), 'shipments', ['customer_id'], unique=False)
    # Named explicitly. Autogenerate passes None here, which lets PostgreSQL
    # invent a name, and the downgrade then cannot drop a constraint it cannot
    # name.
    op.create_foreign_key(
        'fk_shipments_customer_id_users',
        'shipments',
        'users',
        ['customer_id'],
        ['id'],
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(
        'fk_shipments_customer_id_users', 'shipments', type_='foreignkey'
    )
    op.drop_index(op.f('ix_shipments_customer_id'), table_name='shipments')
    op.drop_column('shipments', 'customer_id')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
