"""add user email verification flag

Revision ID: 0e8a5e79dd89
Revises: 7a9f23d93176
Create Date: 2026-09-03 06:42:47.946217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0e8a5e79dd89'
down_revision: Union[str, Sequence[str], None] = '7a9f23d93176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Existing accounts default to unverified. Defaulting them to true would be
    # convenient and would also assert something the system has never checked.
    op.add_column(
        'users',
        sa.Column(
            'is_verified',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
