"""add tracking events table

Revision ID: 14621d8a6fe4
Revises: bf377cbe5e9e
Create Date: 2026-09-03 05:37:45.801650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '14621d8a6fe4'
down_revision: Union[str, Sequence[str], None] = 'bf377cbe5e9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# The shipmentstatus type was created by the shipments migration. Autogenerate
# emits a plain sa.Enum here, which tries to CREATE TYPE a second time and fails
# with DuplicateObjectError. create_type=False references the existing type.
SHIPMENT_STATUS = postgresql.ENUM(
    'placed', 'picked_up', 'in_transit', 'at_warehouse',
    'out_for_delivery', 'delivered', 'cancelled', 'exception',
    name='shipmentstatus',
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('tracking_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('status', SHIPMENT_STATUS, nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=240), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracking_events_recorded_at'), 'tracking_events', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_tracking_events_shipment_id'), 'tracking_events', ['shipment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracking_events_shipment_id'), table_name='tracking_events')
    op.drop_index(op.f('ix_tracking_events_recorded_at'), table_name='tracking_events')
    op.drop_table('tracking_events')
    # ### end Alembic commands ###
