"""create shipments table

Revision ID: bc0216e87869
Revises: 
Create Date: 2026-09-03 04:06:53.676182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Autogenerate emits sqlmodel.sql.sqltypes.AutoString for str columns but does
# not add this import, so the generated file raises NameError until it is here.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bc0216e87869'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('destination', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('placed', 'picked_up', 'in_transit', 'at_warehouse', 'out_for_delivery', 'delivered', 'cancelled', 'exception', name='shipmentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_status'), 'shipments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_shipments_status'), table_name='shipments')
    op.drop_table('shipments')
    # Dropping the table leaves the enum type behind on PostgreSQL, so a
    # downgrade followed by an upgrade fails with "type shipmentstatus already
    # exists". Autogenerate never writes this line; it has to be added by hand.
    sa.Enum(name='shipmentstatus').drop(op.get_bind(), checkfirst=True)
