"""add packages table

Revision ID: bf377cbe5e9e
Revises: 0a8968878aa0
Create Date: 2026-09-03 05:33:44.832541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bf377cbe5e9e'
down_revision: Union[str, Sequence[str], None] = '0a8968878aa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('length_cm', sa.Float(), nullable=False),
    sa.Column('width_cm', sa.Float(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packages_shipment_id'), 'packages', ['shipment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_packages_shipment_id'), table_name='packages')
    op.drop_table('packages')
    # ### end Alembic commands ###
